version: "3.6"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: "INTERNAL://kafka:9090, EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:9090, EXTERNAL://:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT, EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      # topic,partition,replication
      KAFKA_CREATE_TOPICS: "readings:2:1,values:2:1"
    healthcheck:
      test: ["CMD", "nc", "-z", "kafka", "9090"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      - zookeeper
  cli:
    # container with preinstalled kafka cli tools
    image: frser/kafka-cli
